# Site settings
title: Interactive Storytelling
email: us@thesprouts.org
# description: > # this means to ignore newlines until "baseurl:"
   
# baseurl: "/ccp/" # the subpath of your site, e.g. /blog/
baseurl: "/hli/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

# LPs collection
collections:
  people:
    output: true
  code:
    output: true
